apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: user-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend       # ✅ use standard mapping instead of { app: frontend }
    spec:
      containers:
        - name: frontend
          image: localhost:32100/user-login-app-frontend:latest   # ✅ match pushed image
          ports:
            - containerPort: 80
