apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: user-login-app
spec:
  type: NodePort           # ✅ change from ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80